#' Creates a plot to explore two of the environmental predictors in
#' geographic and environmental spaces.
#'
#' @description Creates a four panels plot with the information of two of the
#' environmental predictors in the region of interest. The two top panels contain
#' the information in geographic space (one predictor per panel) and in the two
#' bottom panels contain the information in environmental space (point cloud on
#' the left side and points density on the right side).
#'
#' @param master a master_matrix object derived from function
#' \code{\link{master_matrix}} or a master_selection object derived from functions
#' \code{\link{uniformG_selection}}, \code{\link{uniformE_selection}}
#' or \code{EG_selection}.
#' @param variable_1 (character or numeric) name or position of the first
#' variable (X axis) to be used to create blocks.
#' @param variable_2 (character or numeric) name or position of the second
#' variable (Y axis) to be used to create blocks (must be different from the
#' first one).
#' @param col_variable1 (character) a color palette, i.e. a vector of n contiguous
#' colors generated by functions like \code{\link{rainbow}},
#' \code{\link{heat.colors}}, \code{\link{topo.colors}},
#' \code{\link{bpy.colors}} or one of your own making, perhaps using
#' \code{\link{colorRampPalette}}. Default = NULL
#' @param col_variable2 (character) a color palette, i.e. a vector of n contiguous
#' colors generated by functions like \code{\link{rainbow}},
#' \code{\link{heat.colors}}, \code{\link{topo.colors}},
#' \code{\link{bpy.colors}} or one of your own making, perhaps using
#' \code{\link{colorRampPalette}}. Default = NULL
#' @param col_points (character) a color palette, i.e. a vector of n contiguous
#' colors generated by functions like \code{\link{rainbow}},
#' \code{\link{heat.colors}}, \code{\link{topo.colors}},
#' \code{\link{bpy.colors}} or one of your own making, perhaps using
#' \code{\link{colorRampPalette}}. Default = NULL
#' @param col_density (character) a color palette, i.e. a vector of n contiguous
#' colors generated by functions like \code{\link{rainbow}},
#' \code{\link{heat.colors}}, \code{\link{topo.colors}},
#' \code{\link{bpy.colors}} or one of your own making, perhaps using
#' \code{\link{colorRampPalette}}. Default = NULL
#'
#' @return
#' A multipanel plot showing two of the environmental preditors in the region of
#' interest in both spaces, geographic and environmental.
#'
#' @usage
#' plot_matrix_HD(master, variable_1, variable_2, col_variable1 = NULL,
#'                col_variable2 = NULL, col_points = NULL, col_density = NULL)
#'
#' @export
#' @importFrom ks kde
#' @importFrom viridis viridis cividis
#' @importFrom scales alpha
#' @importFrom sp plot
#' @importFrom raster image
#' @importFrom graphics image layout par plot.new rasterImage text title
#' @importFrom grDevices as.raster
#'
#' @examples
#' # Data
#' data("m_matrix", package = "biosurvey")
#'
#' colnames(m_matrix$master_matrix)
#'
#' # Plot
#' plot_matrix_HD(m_matrix, variable_1 = "PC1", variable_2 = "PC2")


plot_matrix_HD <- function(master, variable_1, variable_2,
                           col_variable1 = NULL, col_variable2 = NULL,
                           col_points = NULL, col_density = NULL) {

  # initial tests
  if (missing(master)) {
    stop("Argument 'master' is required to produce the plot.")
  }
  if (missing(variable_1)) {
    stop("Argument 'variable_1' is required to produce the plot.")
  }
  if (missing(variable_2)) {
    stop("Argument 'variable_2' is required to produce the plot.")
  }
  if (!class(master)[1] %in% c("master_matrix", "master_selection")) {
    stop("Object defined in 'master' is not valid, see function's help.")
  }

  # par settings
  opar <- par(no.readonly = TRUE)
  on.exit(par(opar))

  # kernel
  mx2kd <- ks::kde(master$master_matrix[, c(variable_1, variable_2)])

  # colors
  if (is.null(col_variable1) & is.null(col_variable2) & is.null(col_points) &
      is.null(col_density)) {
    c1 <- viridis::viridis(255)
    c2 <- scales::alpha(c1[25], 0.6)
    c3 <- viridis::cividis(255)
    c4 <- c3
    c1[1] <- NA
  } else {
    if (is.null(col_variable1)) {
      c3 <- viridis::cividis(255)
    }
    if (is.null(col_variable2)) {
      c4 <- viridis::cividis(255)
    }
    if (is.null(col_variable2)) {
      c4 <- viridis::cividis(255)
    }
    if (is.null(col_density)) {
      c1 <- viridis::viridis(255)
    }
    if (is.null(col_points)) {
      c2 <- scales::alpha(viridis::viridis(255)[25], 0.6)
    }
  }

  # limits
  xlim <- range(master$master_matrix[, variable_1])
  ylim  <- range(master$master_matrix[, variable_2])

  # plot
  layout(matrix(1:20, 4, byrow = T), widths = c(1, 10, 2, 10, 2),
                   heights = c(1, 10, 1.2, 10))
  par(cex = 0.7, mar = rep(0, 4))

  ## titles
  plot.new()
  plot.new()
  text(0.5, 0.5, variable_1, cex = 1.2)
  plot.new()
  plot.new()
  text(0.5, 0.5, variable_2, cex = 1.2)
  plot.new()

  ## geographic space
  plot.new()
  text(0.5, 0.5, "Geographic space", cex = 1.2, srt = 90)

  sp::plot(master$polygon, border = NA)
  var <- master$raster_base
  var[!is.na(var[])] <- master$master_matrix[, variable_1]
  value_range <- c(var@data@min, var@data@max)
  raster::image(var, col = c3, add = TRUE)
  sp::plot(master$polygon, add = TRUE)

  plot.new()
  bar_legend(value_range, col = c3, title = variable_1)


  sp::plot(master$polygon, border = NA)
  var[!is.na(var[])] <- master$master_matrix[, variable_2]
  value_range <- c(var@data@min, var@data@max)
  raster::image(var, col = c4, add = TRUE)
  sp::plot(master$polygon, add = TRUE)

  plot.new()
  bar_legend(value_range, col = c3, title = variable_2)

  ## titles
  plot.new()
  plot.new()
  text(0.5, 0.5, "Point cloud", cex = 1.2)
  plot.new()
  plot.new()
  text(0.5, 0.5, "Point density", cex = 1.2)
  plot.new()

  ## environmental space
  plot.new()
  text(0.5, 0.6, "Environmental space", cex = 1.2, srt = 90)

  par(mar = c(3.5, 3.5, 0.5, 0.5))
  plot(master$master_matrix[, c(variable_1, variable_2)], col = c2,
       bty = "l", xlab = "", ylab = "")
  title(xlab = variable_1, line = 2.4, cex.lab = 1.1)
  title(ylab = variable_2, line = 2.4, cex.lab = 1.1)

  par(mar = rep(0, 4))
  plot.new()

  par(mar = c(3.5, 3.5, 0.5, 0.5))
  plot(xlim, ylim, type = "n", bty = "l", xlab = "", ylab = "")
  image(mx2kd$eval.points[[1]], mx2kd$eval.points[[2]],
                  z = mx2kd$estimate, col = c1, add = TRUE)
  title(xlab = variable_1, line = 2.4, cex.lab = 1.1)

  par(mar = rep(0, 4))
  plot.new()
  bar_legend(c("Low", "High"), col = c1, title = "Density", round = 1)
}


